services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: npm run start:dev